server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EmployeeManagementdb
    username: root
    password: Madhuri@43PET
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
